version: '3.8'

services:
  zoom-to-s3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zoom-to-s3
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs 